from pathlib import Path
from lxml import etree
from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH


def generate_chapter2_docx(xml_path: str | Path, output_path: str | Path = "chapter2_output.docx") -> Path:
    """Generate a Word document from Chapter 2 XML with file versioning tables.
    
    Args:
        xml_path: Path to the XML file generated by build_ch2_xml_attr_rows
        output_path: Path where the Word document will be saved
        
    Returns:
        Path to the generated Word document
    """
    xml_path = Path(xml_path)
    output_path = Path(output_path)
    
    # Parse XML
    tree = etree.parse(str(xml_path))
    root = tree.getroot()
    
    # Create Word document
    doc = Document()
    
    # Process the document
    paragraph = root.find(".//paragraph")
    if paragraph is None:
        raise ValueError("No paragraph found in XML")
    
    # Add main chapter title
    chapter_title = paragraph.get("title", "Chapter 2")
    chapter_number = paragraph.get("number", "2")
    
    heading = doc.add_heading(f"{chapter_number}. {chapter_title}", level=1)
    heading.alignment = WD_ALIGN_PARAGRAPH.LEFT
    
    # Process each subparagraph (folder)
    for subpar in paragraph.findall("subparagraph"):
        subpar_number = subpar.get("number", "")
        subpar_title = subpar.get("title", "")
        
        # Add subparagraph heading
        subheading = doc.add_heading(f"{subpar_number} {subpar_title}", level=2)
        subheading.alignment = WD_ALIGN_PARAGRAPH.LEFT
        
        # Find the table element
        table_elem = subpar.find("table")
        if table_elem is not None:
            rows = table_elem.findall("row")
            
            if rows:
                # Create Word table with header
                table = doc.add_table(rows=1, cols=2)
                table.style = 'Light Grid Accent 1'
                
                # Set header row
                header_cells = table.rows[0].cells
                header_cells[0].text = "File Name"
                header_cells[1].text = "Version"
                
                # Make header bold
                for cell in header_cells:
                    for paragraph in cell.paragraphs:
                        for run in paragraph.runs:
                            run.font.bold = True
                
                # Add data rows
                for row_elem in rows:
                    name = row_elem.get("name", "")
                    version = row_elem.get("version", "")
                    
                    row_cells = table.add_row().cells
                    row_cells[0].text = name
                    row_cells[1].text = version
                
                # Set column widths
                for row in table.rows:
                    row.cells[0].width = Inches(4.5)
                    row.cells[1].width = Inches(1.5)
        
        # Add spacing after each section
        doc.add_paragraph()
    
    # Save document
    output_path.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(output_path))
    
    return output_path


if __name__ == "__main__":
    # Test the generator
    xml_file = Path("../../chapter2_new.xml")
    if xml_file.exists():
        output = generate_chapter2_docx(xml_file, "../../chapter2_output.docx")
        print(f"Document generated: {output}")
    else:
        print(f"XML file not found: {xml_file}")