from typing import IO, Iterable

from docx import Document
from document_builder.renderer.renderer import Renderer
from pathlib import Path
from datetime import datetime
from utils import get_logger

logger = get_logger(__name__)

class DocumentBuilder:
    """
    Builder for ``python-docx`` Word documents.

    Follows a simple **builder pattern**: create an instance, chain one or
    more :meth:`add_section` calls (each driven by a :class:`Renderer`),
    then call :meth:`save`.  The underlying ``Document`` object is always
    accessible via ``self.document`` for any additional manual customisation.

    Example
    -------
    ::

        builder = DocumentBuilder(template="template.docx", output_path="out/report.docx")
        builder.add_section(FileVersioningRenderer(xml, config)) \\
               .add_section(TaskVersioningRenderer(xml, config)) \\
               .save()
    """

    def __init__(self, template: str | IO[bytes] | None = None, output_path: str | Path | None = None):
        """
        Parameters
        ----------
        template : str | IO[bytes] | None
            Path to a ``.docx`` template file, or a file-like object opened
            in binary mode.  When ``None`` a blank document is created.
        output_path : str | Path | None
            Destination path for :meth:`save`.  The parent directory is
            created automatically if it does not exist.  When ``None`` the
            document is saved in the current working directory with an
            auto-generated timestamped filename.
        """
        self.document = Document(template) # Note: `Document` can accept `None` as a template, in which case it creates a blank document.

        if output_path is not None and not isinstance(output_path, Path):
            output_path = Path(output_path)
        self.output_path = output_path

        #self.renderer: Renderer | None = None

    def set_renderer(self, renderer: Renderer):
        """
        Attach a renderer to this builder.

        .. note::
            Prefer :meth:`add_section` for direct section generation.
            This method exists for cases where the renderer needs to be
            stored and invoked separately.

        Parameters
        ----------
        renderer : Renderer
            Any concrete :class:`Renderer` subclass.

        Returns
        -------
        DocumentBuilder
            ``self``, to allow method chaining.
        """
        self.renderer = renderer
        return self

    def add_section(self, renderer: Renderer):
        """
        Append a document section generated by ``renderer``.

        Calls :meth:`Renderer.render_section` which writes headings and
        tables directly into ``self.document``.  Multiple calls are allowed;
        each section is appended after the previous one.

        Parameters
        ----------
        renderer : Renderer
            Any concrete :class:`Renderer` subclass (e.g.
            :class:`FileVersioningRenderer`,
            :class:`TaskVersioningRenderer`).

        Returns
        -------
        DocumentBuilder
            ``self``, to allow method chaining.
        """
        renderer.render_section(self.document)

        return self

    #def generate_many(self, renderers: Iterable[Renderer]):
     #   for renderer in renderers:
      #      self.add_chapter(renderer)
      # return self

    def save(self, overwrite: bool = False):
        """
        Save the document to :attr:`output_path` and return the final path.

        Parameters
        ----------
        overwrite : bool
            * ``True``  — write directly to :attr:`output_path`, replacing
              any existing file.
            * ``False`` (default) — append a ``_YYYYMMDD_HHMMSS`` timestamp
              suffix to the stem so existing files are never clobbered.

        Returns
        -------
        Path
            The actual path the file was written to (useful when
            ``overwrite=False`` and the name was modified).

        Notes
        -----
        If :attr:`output_path` is ``None`` the document is saved in the
        current working directory as ``Document_YYYYMMDD_HHMMSS.docx``.
        The parent directory is created automatically if it does not exist.
        """
        if self.output_path is None:
            # if output_path not defined, save in current directory
            self.output_path = Path.cwd() / f"Document_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"

        self.output_path.parent.mkdir(parents=True, exist_ok=True)

        if overwrite:
            save_path = self.output_path
        else:
            # Simple, cheap strategy: append a short timestamp suffix.
            suffix = datetime.now().strftime("_%Y%m%d_%H%M%S")
            save_path = self.output_path.with_name(f"{self.output_path.stem}{suffix}{self.output_path.suffix}")

        self.document.save(str(save_path))

        return save_path